x = int(input("Enter first number: "))
y = int(input("Enter second number: "))
print("Addition =", x + y)
print("Subtraction =", x - y)
print("Multiplication =", x * y)
print("Division =", x / y)
print("Modulus =", x % y)